-- Run this once in the Supabase SQL editor.
-- Scraped shows stay in Events_table. User-added shows go here so the daily scrape cannot wipe them.

create table if not exists public.user_submitted_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  date text,
  raw_date text,
  venue text,
  city text,
  genre text,
  ticket_info text,
  organizer text,
  event_url text,
  event_link_url text,
  event_link_text text,
  created_at timestamptz not null default now()
);

create index if not exists user_submitted_events_raw_date_idx
  on public.user_submitted_events (raw_date);
